{% set name = "napari-graph" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-graph-{{ version }}.tar.gz
  sha256: 144246c9fa357660a47b477a743be146344b27c5f75880be1158e975712bfe90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - networkx
    - numba
    - numpy
    - pandas
    - python >={{ python_min }},<3.11

test:
  imports:
    - napari_graph
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-graph
  summary: Efficient graph data structures and algorithms for fast slicing, visualization, and editing
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/napari/napari-graph

extra:
  recipe-maintainers:
    - DragaDoncila
    - goanpeca
    - jaimergp
    - kephale
    - kevinyamauchi
